apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-onprem.fullname" . }}-ros-processor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
    app.kubernetes.io/name: ros-processor
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ros.processor.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cost-onprem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: processor
    app.kubernetes.io/name: ros-processor

