apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-mgmt.koku.api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.koku.labels" . | nindent 4 }}
    app.kubernetes.io/component: cost-management-api
spec:
  type: {{ .Values.costManagement.api.service.type }}
  ports:
  - name: http
    port: {{ .Values.costManagement.api.service.port }}
    targetPort: {{ .Values.costManagement.api.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "cost-mgmt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cost-management-api

