{{- if .Values.trino.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-service-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: trino
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
{{- end }}

