apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-ros-rec-poller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: recommendation-poller
    app.kubernetes.io/name: ros-rec-poller
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ros.recommendationPoller.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cost-mgmt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: recommendation-poller
    app.kubernetes.io/name: ros-rec-poller

