apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-onprem.fullname" . }}-ros-rec-poller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: recommendation-poller
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ros.recommendationPoller.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cost-onprem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: recommendation-poller

