apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-onprem.fullname" . }}-sources-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: sources-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.sourcesApi.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cost-onprem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: sources-api