apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-mgmt.trino.coordinator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: trino-coordinator
spec:
  type: {{ .Values.trino.coordinator.service.type }}
  ports:
  - name: http
    port: {{ .Values.trino.coordinator.service.port }}
    targetPort: {{ .Values.trino.coordinator.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "cost-mgmt.trino.coordinator.selectorLabels" . | nindent 4 }}

