apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-kruize
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
    app.kubernetes.io/component: optimization
    app.kubernetes.io/name: kruize
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kruize.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cost-mgmt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: optimization
    app.kubernetes.io/name: kruize