apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-onprem.fullname" . }}-kruize
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: ros-optimization
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kruize.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cost-onprem.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ros-optimization
