apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cost-mgmt.fullname" . }}-cdapp-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.labels" . | nindent 4 }}
data:
  cdappconfig.json: |
    {
      "database": {
        "adminPassword": "{{ .Values.database.ros.password }}",
        "adminUsername": "{{ .Values.database.ros.user }}",
        "hostname": "{{ include "cost-mgmt.database.host" (list . "ros") }}",
        "name": "{{ .Values.database.ros.name }}",
        "password": "{{ .Values.database.ros.password }}",
        "port": {{ .Values.database.ros.port }},
        "username": "{{ .Values.database.ros.user }}",
        "sslMode": "{{ .Values.database.ros.sslMode }}"
      },
      "kafka": {
        "brokers": [
          {
            "hostname": "{{ include "cost-mgmt.kafka.host" . }}",
            "port": {{ include "cost-mgmt.kafka.port" . }}
          }
        ],
        "topics": [
          {
            "name": "{{ .Values.ros.processor.uploadTopic }}",
            "requestedName": "{{ .Values.ros.processor.uploadTopic }}"
          },
          {
            "name": "{{ .Values.ros.recommendationPoller.recommendationTopic }}",
            "requestedName": "{{ .Values.ros.recommendationPoller.recommendationTopic }}"
          },
          {
            "name": "{{ .Values.sourcesApi.platformSourcesEventStreamTopic }}",
            "requestedName": "{{ .Values.sourcesApi.platformSourcesEventStreamTopic }}"
          }
        ]
      },
      "logging": {
        "type": "null"
      },
      "metricsPath": "/metrics",
      "metricsPort": 9000,
      "privatePort": 10000,
      "publicPort": 8000,
      "webPort": 8000
    }