apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-mgmt.trino.metastore.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-mgmt.trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive-metastore
spec:
  type: {{ .Values.trino.metastore.service.type }}
  ports:
  - name: thrift
    port: {{ .Values.trino.metastore.service.port }}
    targetPort: {{ .Values.trino.metastore.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "cost-mgmt.trino.metastore.selectorLabels" . | nindent 4 }}

